config/routes.rb
Bigredbutton::Application.routes.draw do

  
  get "notes/index_all"

  get "groups/index"

  resources :notes
  resources :tasks

  resources :time_records

  root :to => 'time_records#new'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :time_record_ids, :note_ids, :hours, :minutes
  belongs_to :group
  has_many :time_records
  has_many :notes





end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    update_time(@tasks)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create

    @task = Task.new(params[:task])

     @task.hours = 0
    @task.minutes = 0
    # binding.pry
    if params["time_record"]
      time_record = TimeRecord.find(params["time_record"])
    end

    # binding.pry

    respond_to do |format|
      if @task.save
      
        if time_record
          @task.time_records << time_record
        end
        format.js
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private


  def update_time(tasks)

    tasks.each do |p|

      unless  p.time_records.where(state: "toallocate").empty?

        time_records = p.time_records.where(state: "toallocate")

        hours =  time_records.map {|t| t.hours}.reduce(:+)
        minutes = time_records.map {|t| t.minutes}.reduce(:+)

      

        if minutes >= 60 

          hours_to_add = minutes/60
       
          hours +=hours_to_add
         
          minutes  = minutes - hours_to_add * 60
  
        end

        
        p.hours += hours
        p.minutes += minutes


      

        if p.minutes > 59

           hours_to_add_x = p.minutes/60

           p.hours += hours_to_add_x

           p.minutes = p.minutes - hours_to_add_x * 60

        end

        p.save

        time_records.each do |tr|
          tr.state = "closed"
          tr.save
        end
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="well well-sm task clickable-div" value="<%=task.id %>">
<%=task.name %><span class="badge pull-right clickable-div"><sm>Time : <%=task.hours %> hrs  :  <%=task.minutes %> mins</sm></span></div>

app/views/tasks/_tasks.html.erb
  <div id="full_tasks">
      <% if @tasks %>
      <h3>Tasks</h3>
        <% @tasks.each do |task| %>
        <div class="well well-sm task clickable-div" value="<%=task.id %>">
        <%=task.name %><span class="badge pull-right clickable-div"><sm>Time : <%=task.hours %> hrs  :  <%=task.minutes %> mins</sm></span></div>
        <% end %>
      <% end %>
    </div>

app/views/tasks/create.js.erb
$('#task_name').val('')
$('.new_task').fadeOut();
$('.select_a_task').fadeOut();
$('#note_task_id').val("<%=@task.id%>");
$('#time_record_header').text("<%=@task.name%>");
$('#note_content').prop('disabled', false);
$('#note_content').prop('placeholder', 'Add something...');
$('#note_message').fadeOut();
$('#task_prompt').fadeOut();
$('#bigredbutton').val("Press to finish time on: \n <%=@task.name %>");

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class = "row">
  <div class="col-sm-10 col-sm-offset-1">

<h2>Tasks with time recording and notes</h2>

<table class="table table-bordered table-responsive">
  <tr>
    <th>name</th>
    <th>No. of time records</th>
    <th>Hours spent</th>
    <th>Minutes spent</th>
    <th>No. of notes</th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.name, task %></td>
    <td><%= task.time_records.count %></td>
    <td><%= task.hours %></td>
    <td><%= task.minutes %></td>
    <td><%= task.notes.count %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Start time record', new_time_record_path %>
</div>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="row">
	<div class="col-sm-10 col-sm-offset-1">

<h2> Task details, time records and notes</h2>

<h3>
  <b>name:</b>
  <%= @task.name %>
</h3>


<p id="notice"><%= notice %></p>


		<h4> Time Records </h4>
			<table class="table table-bordered table-responsive">
	  <tr>
	    <th>State</th>
	    <th>Hours</th>
	    <th>Minutes</th>
	    <th>Recorded on</th>
	  </tr>



	<% @task.time_records.each do |time_record| %>
	<tr>
		<td><%= time_record.state %></td>
		<td><%= time_record.hours %></td>
		<td><%= time_record.minutes %></td>
		<td><%= time_record.updated_at.strftime("%d/%m/%y") %></td>
	</tr>
	<% end %>
	</table>


	<h4> Task Notes </h4>
			<table class="table table-bordered table-responsive">

	<col width="80%">
  	<col width="20%">
	  <tr>
	    <th >Content</th>
	    <th>Created at</th>
	  </tr>



	<% @task.notes.each do |note| %>
	<tr>
		<td ><%= dat_markdown(note.content) %></td>
		<td style="width: 20%;"><%=	note.created_at.strftime("on %d/%m/%y")%>

			<%= link_to 'Edit', edit_note_path(note) %>

		</td>
	</tr>
	<% end %>
	</table>





<%= link_to 'Add more time', new_time_record_path %> |
<%= link_to 'To tasks list', tasks_path %>

	




	</div>
</div>