config/routes.rb
Bigredbutton::Application.routes.draw do

  
  get "notes/index_all"

  get "groups/index"

  resources :notes
  resources :tasks

  resources :time_records

  root :to => 'time_records#new'

end

app/models/time_record.rb
class TimeRecord < ActiveRecord::Base
  attr_accessible :hours, :minutes, :state, :task_id

  belongs_to :task

  def calculate_time(record)
    time = []
    time_milli = record.updated_at - record.created_at

    record.hours = (time_milli/(60*60)).to_i
    record.minutes = ((time_milli - hours.round * (60*60))/(60)).to_i
    record.save

  end
end

app/controllers/time_records_controller.rb
class TimeRecordsController < ApplicationController
  # GET /time_records
  # GET /time_records.json
  def index
    @time_records = TimeRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_records }
    end
  end

  # GET /time_records/1
  # GET /time_records/1.json
  def show
    @time_record = TimeRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_record }
    end
  end

  # GET /time_records/new
  # GET /time_records/new.json
  def new
    @time_record = TimeRecord.new
    @task = Task.new
    @note = Note.new
  
    @operation = "create"
    @status = "open"
    @notes = Note.all


    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /time_records/1/edit
  def edit
    @operation = "update"
    @status = "toallocate"
    @note = Note.new
    @notes = Note.all
    # @task = Task.new
    # @tasks = Task.all
    @groups = Group.order(:name).includes(:tasks)


    @time_record = TimeRecord.find(params[:id])

    unless @time_record.task_id.nil?

      @task = Task.find(@time_record.task.id)
    else
      @task =Task.new
      @groups = Group.order(:name).includes(:tasks)
      @tasks= Task.where("name!=?","unallocated")
    end
  end

  # POST /time_records
  # POST /time_records.json
  def create

    # binding.pry

    unless params[:name].nil?

    if Task.where(name: params[:name]).exists?

      task = Task.find_by_name(params[:name])
        else
      task = Task.create(name: params["name"])
      end
      @time_record = TimeRecord.new(state: "open", task_id: task.id)

    else
        @time_record = TimeRecord.new(state: "open")

    end



    respond_to do |format|
      if @time_record.save
        if task
          task.time_records << @time_record
        end
        format.html { redirect_to edit_time_record_path(@time_record), notice: 'Time record was successfully created.' }
        format.json { render json: @time_record, status: :created, location: @time_record }
      else
        format.html { render action: "new" }
        format.json { render json: @time_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /time_records/1
  # PUT /time_records/1.json
  def update
    @time_record = TimeRecord.find(params[:id])

    # binding.pry

    if @time_record.task_id.nil?

      if Task.all.count == 1
        # binding.pry

          @task = Task.find_by_name("unallocated")

      else


        if params[:Task].empty?
        # binding.pry


          @task = Task.find_by_name("unallocated")

        else 
        # binding.pry


          @task = Task.find(params[:Task])

        end

      end
    else

      @task = Task.find(@time_record.task.id)

    end

    # @time_record.task = @task

    respond_to do |format|
      if @time_record.update_attributes(state: params["status"])
        # binding.pry
        @time_record.calculate_time(@time_record)

        # binding.pry
        if @time_record.task_id.nil?
          @time_record.task = @task
          @time_record.save
        end


        format.html { redirect_to @task, notice: 'Time record was successfully updated with more time.' }
      
      else
        format.html { render action: "edit" }
        format.json { render json: @time_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_records/1
  # DELETE /time_records/1.json
  def destroy
    @time_record = TimeRecord.find(params[:id])
    @time_record.destroy

    respond_to do |format|
      format.html { redirect_to time_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/time_records_helper.rb
module TimeRecordsHelper
end

app/views/time_records/_clock.html.erb
<div >
	<h3 id="clock_message"></h3>
	<div id="hours" style="display:inline;"></div>
	<div id="minutes" style="display:inline;"></div>
	<div id="seconds" style="display:inline;"></div>
</div>

app/views/time_records/_form.html.erb
<div class="row">
	<div class="col-sm-12">
		<h2 id="time_record_header">Start something new</h2>
	</div>
</div>



  <div class="row">
   
      <div class="col-sm-4">

        <%= render "clock" %>

        <%= render "new_task" %>

        <%= render "time_record_form" %>

        <%= render "notes_form" %>
      </div>

      <div class="col-sm-4">

      <%= render "groups/groups" %>


      <%= render "tasks/tasks" %>

    <h3 id="partial_tasks_header" style="display:none;">Tasks</h3>
    <div id="tasks">

    </div>



      </div>

  </div>

app/views/time_records/_mobile_form.html.erb
<div class="row">
  <div class="col-xs-11 col-xs-offset-1 ">
    <h2 id="time_record_header">Start something new</h2>
  
  </div>
</div>

<div>

<div class="row">
  <div class="col-xs-11 col-xs-offset-1 ">
     <%= render "clock" %>
     <%= render "time_record_form" %>

    <%= render "new_task" %>

  </div>
</div>

<div class="row">
  <div class="col-xs-11 col-xs-offset-1 ">

        <%= render "notes_form" %>

  </div>
</div>

app/views/time_records/_new_task.html.erb
<% if !@time_record.id.nil? %>

  <% if !@task.id.nil?  && !@time_record.id.nil? %>

    <p> Timing for task: <%= @task.name %></p>


    <% elsif !@time_record.id.nil? && @task.id.nil? %>

    <h3 id="task_prompt">Give your new task a name!</h3>

      <%= form_for @task, :remote=> true, url: {action: "create", controller: "tasks"} do |f| %>


      <%= hidden_field_tag "time_record", @time_record.id %>
       <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="actions">
        <%= f.submit "New task",id:"new_task_button", class: "btn btn-success" %>
      </div>

    <% end %>

  <% end %>
<% end %>

app/views/time_records/_notes_form.html.erb
<% unless @time_record.id.nil? %>

<%= form_for @note, url: {action: "create", controller: "notes"}, :remote=> true do |g| %>

	<%= hidden_field_tag "note_task_id" %>

  <div class="field">
    <%= g.label :content, "New note" %><br />
    <%= g.text_area :content, rows:"5", cols:"40", disabled: true, class: "disabled",:placeholder => "Select or create a task to add notes"%>
  </div>
  <div class="actions">
    <%= g.submit "Add note", class: "btn btn-success" %>
  </div>
<% end %>


<ul id="notes">
</ul>

<% end %>

app/views/time_records/_time_record_form.html.erb
<%= form_for @time_record do |f| %>

    <%=hidden_field_tag "operation", @operation %>
    <%=hidden_field_tag "status", @status %>

  <% if !@time_record.id.nil? && @tasks.count > 0 %>
    <% if @task.id.nil? %>
      <div class="field select_a_task">
        <br/>
        <%= label_tag "Select a previous task" %><br />
        <%= select_tag "Task", options_from_collection_for_select(@tasks, "id", "name"), :include_blank => "Select task" %>
      </div>
    <% end %>
  <% end %>
<!-- 
    <div id="bigredbutton" class="clickable-div">Time Please!</div> -->


    <div class="actions">

      <% if @operation == "create" %>
        <% buttoncolor = "red" %>
        <% buttontext = "Get Started!" %>
      <% else %>
        <% buttoncolor = "blue "%>
        <% buttontext = "Press to Finish" %>
      <% end %>


      <%= f.submit buttontext, class: "clickable-div #{buttoncolor}", id: "bigredbutton" %>
    </div>
  <% end %>

app/views/time_records/edit.html.erb
<div class="container">
	<%= render 'form' %>
</div>	

app/views/time_records/index.html.erb
<h1>Listing time_records</h1>

<table>
  <tr>
    <th>Task</th>
    <th>State</th>
    <th>Hours</th>
    <th>Minutes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @time_records.each do |time_record| %>
  <tr>
    <td><%= time_record.task.name %></td>
    <td><%= time_record.state %></td>
    <td><%= time_record.hours %></td>
    <td><%= time_record.minutes %></td>
    <td><%= link_to 'Show', time_record %></td>
    <td><%= link_to 'Edit', edit_time_record_path(time_record) %></td>
    <td><%= link_to 'Destroy', time_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Time record', new_time_record_path %>

app/views/time_records/new.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-11 col-xs-offset-1 col-sm-offset-1">
	
		<%= render 'form' %>

	<%=link_to "Review tasks", tasks_path %>
	</div>
</div>
</div>

app/views/time_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @time_record.task_id %>
</p>

<p>
  <b>State:</b>
  <%= @time_record.state %>
</p>

<p>
  <b>Hours:</b>
  <%= @time_record.hours %>
</p>

<p>
  <b>Minutes:</b>
  <%= @time_record.minutes %>
</p>


<%= link_to 'Edit', edit_time_record_path(@time_record) %> |
<%= link_to 'Back', time_records_path %>